<a href="https://colab.research.google.com/github/tonni59/Numpy/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Creating Arrays from Existing Data


In [1]:
import numpy as np
numbers = np.array([2,3,5,7,11])
numbers

array([ 2,  3,  5,  7, 11])

In [2]:
arr_0 = np.array([])
arr_0

array([], dtype=float64)

In [3]:
arr_0.ndim

1

In [4]:
type(numbers)

numpy.ndarray

**Dimension**


1D array


In [5]:
arr_0 = np.array(2)
arr_0

array(2)

In [6]:
print(type(arr_0))

<class 'numpy.ndarray'>


In [7]:
array_1 = np.array([2])
array_1

array([2])

In [8]:
array_1D = np.array([2,3,4,5,6])
array_1D

array([2, 3, 4, 5, 6])

2D array


In [9]:
arr_2 = np.array([[1,2,3,4]])
arr_2

array([[1, 2, 3, 4]])

In [10]:
arr_2.ndim

2

In [11]:
array_2D = np.array([[2,4,5,6],[2,4,5,6],[2,4,5,6]])
array_2D

array([[2, 4, 5, 6],
       [2, 4, 5, 6],
       [2, 4, 5, 6]])

In [12]:
array_2D.shape

(3, 4)

3D array


In [25]:
array_3D = np.array([[[[2,4,5,6],[2,4,5,6],[2,4,5,6]]]])
array_3D

array([[[[2, 4, 5, 6],
         [2, 4, 5, 6],
         [2, 4, 5, 6]]]])

In [26]:
array_3D.shape

(1, 1, 3, 4)

**Array Attributes**


In [13]:
integers = np.array([[1,2,3],[4,5,6]])
integers

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
floats = np.array([0.0,0.1,0.2,0.3,0.4])
floats

array([0. , 0.1, 0.2, 0.3, 0.4])

In [15]:
strings = np.array(['apple','big','cat'])
strings

array(['apple', 'big', 'cat'], dtype='<U5')

Checking Arrays element types


In [16]:
integers.dtype

dtype('int64')

In [17]:
floats.dtype

dtype('float64')

Checking an array's Dimensions and shape


In [19]:
array_1D.ndim

1

In [20]:
array_2D.ndim

2

In [27]:
array_3D.ndim

4

In [28]:
integers

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
integers.ndim

2

In [30]:
integers.shape

(2, 3)

In [31]:
integers.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [32]:
array_2D.shape

(3, 4)

Checking an array’s Number of Elements and Element Size


In [33]:
integers.size

6

In [34]:
floats.size

5

**Array Operators**


In [35]:
x = np.arange(4)
x

array([0, 1, 2, 3])

In [36]:
x+10

array([10, 11, 12, 13])

In [37]:
x*2

array([0, 2, 4, 6])

In [38]:
x*x

array([0, 1, 4, 9])

In [39]:
x/10

array([0. , 0.1, 0.2, 0.3])

In [40]:
x//10

array([0, 0, 0, 0])

In [41]:
x**3

array([ 0,  1,  8, 27])

In [44]:
x = np.array([[11,9,11],[2,15,18]])
x

array([[11,  9, 11],
       [ 2, 15, 18]])

In [45]:
x>10

array([[ True, False,  True],
       [False,  True,  True]])

In [46]:
x>=10

array([[ True, False,  True],
       [False,  True,  True]])

In [47]:
x<10

array([[False,  True, False],
       [ True, False, False]])

In [48]:
x==9

array([[False,  True, False],
       [False, False, False]])

In [49]:
x!=11

array([[False,  True, False],
       [ True,  True,  True]])

**NumPy Function**


In [50]:
grades = np.array([[87,96,70],[100,87,90],
                   [94,77,90],[100,81,82]])
grades

array([[ 87,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])

In [51]:
grades.max()

100

In [53]:
grades.min()

70

In [54]:
grades.sum()

1054

In [55]:
grades.std()

8.792357792739987

In [56]:
grades.mean()

87.83333333333333

In [57]:
grades.var()

77.30555555555556

In [58]:
grades.mean(axis=0)

array([95.25, 85.25, 83.  ])

In [59]:
grades.mean(axis=1)

array([84.33333333, 92.33333333, 87.        , 87.66666667])

**Indexing and Selection**


In [61]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [62]:
arr_2d[2]

array([35, 40, 45])

In [ ]:
arr_2d[0][2]

In [ ]:
arr_2d[1]

In [ ]:
arr_2d[:,:2]